<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asmc</string>
	</array>
	<key>name</key>
	<string>ASMC Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(psh|pop|flsh|size|last)\b</string>
			<key>name</key>
			<string>keyword.stack.asmc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(WRT|MOVE)\b</string>
			<key>name</key>
			<string>keyword.pointer.asmc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(NAND|NEQ|GREQ|LSEQ|GRTR|LESS|EQ)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.asmc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(MULT|AND|XNOR|XOR|NOT|RGHT|LEFT|SUB|ADD|NOP)\b</string>
			<key>name</key>
			<string>keyword.operator.math.asmc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(IBX|IAX|OCX|OBX|OAX|PAX|AX|DCX|DBX|DAX)\b</string>
			<key>name</key>
			<string>variable.register.asmc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.asmc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(move|OP|Stck|pnt|NOP)\b</string>
			<key>name</key>
			<string>keyword.instruction_type.asmc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>0x.*$</string>
			<key>name</key>
			<string>variable.address.asmc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\b\\d+\\b</string>
			<key>name</key>
			<string>constant.numeric.asmc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>punctuation.separator.comma.asmc</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asmc</string>
	<key>uuid</key>
	<string>cdea207a-7258-44b8-8278-583ad3aac858</string>
</dict>
</plist>
